OrderNow.Web/Controllers/CartController.cs
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using OrderNow.Domain.Entities;
using OrderNow.Domain.Services;
using OrderNow.Web.Models.ViewModel;

namespace OrderNow.Web.Controllers;
public class CartController : Controller
{
    private readonly ICartService _cartService;
    private readonly IProductService _productService;
    private readonly IMapper _mapper;
    public CartController(ICartService cartService,
        IProductService productService,
        IMapper mapper
        )
    {
        _cartService = cartService;
        _productService = productService;
        _mapper = mapper;
    }
    public IActionResult Index()
    {
       var items=_cartService.GetCartItems();
       var itemvm=_mapper.Map<List<CartItem>>(items);
        var viewItem = new CartItemVM
        {
            CartItems = itemvm,
            TotalPrice = _cartService.GetCartTotalPrice()
        };
        return View(viewItem);
    }
    [HttpGet]
    public async Task<IActionResult> AddToCart(int id)
    {
        var productVM = await _productService.GetProductByIdAsync(id);
        if (productVM == null) return NotFound();

        var productEntity = _mapper.Map<Product>(productVM);
        _cartService.AddToCart(productEntity);

        return RedirectToAction("Index");
    }
    public async Task< IActionResult> RemoveFromCart(int id)
    {
        var cart = await _productService.GetProductByIdAsync(id);
        if(cart !=null)
        {
            _cartService.RemoveFromCart(cart);
        }
        return RedirectToAction("Index");
    }
    public async Task<IActionResult> AddItemToCart(int id)
    {
        var cart = await _productService.GetProductByIdAsync(id);
        if (cart != null)
        {
            _cartService.AddToCart(cart);
        }
        return RedirectToAction("Index");
    }
}

OrderNow.Web/Controllers/OrderController.cs
using System.Security.Claims;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OrderNow.Application.Services;
using OrderNow.Domain.Entities;
using OrderNow.Domain.Services;
using OrderNow.Web.Models.ViewModel;

namespace OrderNow.Web.Controllers;
public class OrderController : Controller
{
    private readonly IOrderService _orderService;
    
    private readonly ICartService _cartService;
    private readonly IMapper _mapper;
    public OrderController(IOrderService orderService
        ,ICartService cartService,
        IMapper mapper
        )
    {
        _orderService = orderService;
        
        _cartService = cartService;
        _mapper = mapper;
    }
    [Authorize(Roles ="Admin")]
    public IActionResult Index()
    {
       var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
         var userRole = User.FindFirstValue(ClaimTypes.Role);
        var orders = _orderService.GetOrdersByUserIdAndRoleAsync(userId, userRole);
        return View(orders);
    }

    public  IActionResult CheckOut()
{
        if (!User.Identity.IsAuthenticated)
        {
            return RedirectToAction("Login", "Account");
        }

        var items = _cartService.GetCartItems();
    var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
    var userEmailAddress = User.FindFirstValue(ClaimTypes.Email);
     _orderService.CreateOrder(items, userId, userEmailAddress);
    _cartService.ClearCart();

    return RedirectToAction("OrderConfirmation");
}
    public IActionResult OrderConfirmation()
    {
        return View();
    }


}

OrderNow.Web/Controllers/ProductController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OrderNow.Domain.Entities;
using OrderNow.Domain.Services;
using OrderNow.Web.Models.ViewModel;

namespace OrderNow.Web.Controllers;
[Authorize(Roles = "Admin")]
public class ProductController : Controller
{
    private readonly IProductService _productService;
    private readonly ICategoryService _categoryService;
    private readonly IMapper _mapper;
    public ProductController(
        IProductService productService,
        ICategoryService categoryService,
        IMapper mapper
        )
    {
        _productService = productService;  
        _categoryService = categoryService;
        _mapper = mapper;
    }
    [AllowAnonymous]
    public async Task<IActionResult> ProductList()
    {
      var product=await _productService.GetAllProduct();
       var viewproduct=_mapper.Map<IEnumerable< ProductVM >>(product);
        return View( viewproduct );
    }
    public async Task<IActionResult> Add()
    {
        var viewModel = new ProductVM
        {
            Categories =await _categoryService.AllCategoriesAsync()
                          
        };

        return View(viewModel);
    }
    [HttpPost]
    public async Task<IActionResult> Add(ProductVM viewModel)
    {
        if (ModelState.IsValid)
        {
            var product = _mapper.Map<Product>(viewModel);

           await _productService.AddProductAsync(product);
            TempData["ProductCreated"] = "New Product has been added.";
            return RedirectToAction("ProductList");
        }

        // If validation fails, re-populate categories
        viewModel.Categories =await _categoryService.AllCategoriesAsync();

        return View(viewModel);
    }
    [AllowAnonymous]
    public async Task<IActionResult> Details(int id)
    {
        var product = await _productService.GetProductByIdAsync(id);
        var viewproduct=_mapper.Map<ProductVM>(product);    
        if(product == null)
        {
            return NotFound();
        }
        return View(viewproduct);
    }
    public async Task<IActionResult> Edit(int id)
    {
        var product = await _productService.GetProductByIdAsync(id);
        if (product == null)
        {
            return NotFound();
        }
        var viewModel = _mapper.Map<ProductVM>(product);
        viewModel.Categories = await _categoryService.AllCategoriesAsync();
        return View(viewModel);
    }
    [HttpPost]
    public async Task<IActionResult> Edit(ProductVM viewModel)
    {
        if (ModelState.IsValid)
        {
            var product = _mapper.Map<Product>(viewModel);
            await _productService.UpdateProductAsync(product);
            TempData["ProductUpdated"] = "Product has been updated.";
            return RedirectToAction("ProductList");
        }
        // If validation fails, re-populate categories
        viewModel.Categories = await _categoryService.AllCategoriesAsync();
        return View(viewModel);
    }
    public async Task<IActionResult> Delete(int id)
    {
        var product = await _productService.GetProductByIdAsync(id);
        if(product ==null)
        {
            return NotFound();
        }
        await _productService.DeleteProductAsync(id);
        return RedirectToAction("ProductList");
    }
}

OrderNow.Web/Views/Cart/Index.cshtml
@model OrderNow.Web.Models.ViewModel.CartItemVM
@{
    ViewData["Title"] = "Index";
}

<h3 class="my-3">
    Shopping Cart
</h3>
<div class="container mt-4">
    <div class="row">
        <div class="col-md-8 mx-auto">
            <div class="text-center mb-4">
                <h2>Your Shopping Cart Summary</h2>
            </div>

            <div class="table-responsive">
        <table class="table table-bordered text-center">
            <thead class="table-dark">
                <tr>
                    <th>Amount</th>
                    <th>Product</th>
                    <th>Price</th>
                    <th>Subtotal</th>
                    <th>Actions</th>
                </tr>
            </thead>
            
            <tbody>

        @foreach (var line in Model.CartItems)
        {
            <tr>
                
                <td class="align-middle">@line.Quantity</td>
                <td class="align-middle">@line.Product.ProductName</td>
                                <td >
                                    <div class="fw-bold text-dark">
                                        <span style="font-weight: 900;">৳</span>@Model.TotalPrice.ToString("N2")
                                    </div>
                                </td>
                                <td >
                                    <div class="fw-bold text-dark">
                                        <span style="font-weight: 900;">৳</span>@Model.TotalPrice.ToString("N2")
                                    </div>
                                    </td>
                <td class="align-middle">
                                    <a class="btn btn-sm btn-danger" asp-controller="Cart" asp-action="RemoveFromCart"
                       asp-route-id="@line.Product.Id">
                        <i class="bi bi-dash-circle"></i>
                    </a>
                                    <a class="btn btn-sm btn-success" asp-controller="Cart" asp-action="AddItemToCart"
                       asp-route-id="@line.Product.Id">
                        <i class="bi bi-plus-circle"></i>
                    </a>
                </td>
            </tr>
        }
        </tbody>
        <tfoot class="table-light">
            <tr>
                <td colspan="2"></td>
                <td><b>Total:</b></td>
                            <td>
                                <div class="fw-bold text-danger">
                                    <span style="font-weight: 900;">৳</span>@Model.TotalPrice.ToString("N2")
                                </div>
                            </td>
                           
                <td></td>
            </tr>
        </tfoot>
        </table>
    </div>

    <div class="d-flex justify-content-end gap-2">
        <div id="paypal-btn"></div>
        <a class="btn btn-outline-success" asp-action="CheckOut"asp-controller="Order">
                    CheckOut
        </a>
        <a class="btn btn-outline-success" asp-controller="Product" asp-action="ProductList">
            <i class="bi bi-plus-circle"></i> Add More Items
        </a>
    </div>
</div>
    </div>
</div>